name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "test_*.py" -v

      - name: Build Docker image
        run: |
          docker build -t devops-practice:latest .

      - name: Run Docker container
        run: |
          docker run -d --name devops-practice -p 8000:8000 devops-practice:latest

      - name: Wait for application
        run: |
          sleep 3

      - name: Check application health
        run: |
          curl --fail http://localhost:8000/health

      - name: Show container logs
        if: always()
        run: |
          docker logs devops-practice

      - name: Stop Docker container
        if: always()
        run: |
          docker stop devops-practice

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Docker image
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          docker tag devops-practice:latest "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:latest"
      - name: Deploy to Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
